return {
    -- =========================================================================
    -- Favorites
    -- =========================================================================

    { "rafikdraoui/couleurs.vim",            lazy = false },
    { "kooparse/vim-color-desert-night",     lazy = false },

    { "ChausseBenjamin/friffle-vim",         lazy = false },
    { "srcery-colors/srcery-vim",            lazy = false },

    { "ellisonleao/gruvbox.nvim",            lazy = false, opts = { contrast = "hard", transparent_mode = true } },
    { "sainnhe/gruvbox-material",            lazy = false },
    { "thembones79/mine-pine",               lazy = false },

    -- Mono White
    { "conweller/endarkened.vim",            lazy = false },
    { "kungfusheep/mfd.nvim",                lazy = false },

    -- =========================================================================
    -- Others
    -- =========================================================================
    { "jlobos/camila",                       lazy = false },
    { "aditya-azad/candle-grey",             lazy = false },
    { "cranberry-clockworks/coal.nvim",      lazy = false },
    { "EdenEast/nightfox.nvim",              lazy = false },
    { "mlopes/vim-farin",                    lazy = false },
    { "valonmulolli/heap.nvim",              lazy = false },
    { "katawful/kat.vim",                    lazy = false },
    { "oskarnurm/koda.nvim",                 lazy = false },
    { "tahayvr/matteblack.nvim",             lazy = false },
    { "thembones79/mine-pine",               lazy = false },
    { "gf3/molotov",                         lazy = false },
    { "gleich/monovibrant",                  lazy = false },
    { "piyush-ppradhan/naysayer.vim",        lazy = false },
    { "nocksock/nazgul-vim",                 lazy = false },
    { "bluz71/vim-nightfly-colors",          lazy = false },
    { "rmccorm4/pynux",                      lazy = false },
    { "paulfrische/reddish.nvim",            lazy = false },
    { "elvessousa/sobrio",                   lazy = false },
    { "nikolvs/vim-sunbather",               lazy = false },
    { "mdlerch/tungsten.vim",                lazy = false },
    { "danishprakash/vim-yami",              lazy = false },
    { "jedireza/vim-rizzle",                 lazy = false },
    { "kevinlawler/amberchrome",             lazy = false },
    { "LuRsT/austere.vim",                   lazy = false },
    { "sff1019/hogwarts.vim",                lazy = false },
    { "tomotargz/kuro.vim",                  lazy = false },
    { "mhartington/oceanic-next",            lazy = false },
    { "fcpg/vim-orbital",                    lazy = false },
    { "reconquest/vim-colorscheme",          lazy = false },
    { "smallwat3r/vim-simplicity",           lazy = false },
    { "TaurusOlson/creature.vim",            lazy = false },
    { "lifepillar/vim-gruvbox8",             lazy = false },
    { "Mofiqul/adwaita.nvim",                lazy = false },
    { "dru89/vim-adventurous",               lazy = false },
    { "pedrominicz/focus",                   lazy = false },
    { "mitsuhiko/fruity-vim-colorscheme",    lazy = false },
    { "dapine/mercury",                      lazy = false },
    { "nonetallt/vim-neon-dark",             lazy = false },
    { "senran101604/neotrix.vim",            lazy = false },
    { "lanox/lanox-vim-theme",               lazy = false },
    { "mrpbennett/vault",                    lazy = false },
    { "gerardbm/vim-atomic",                 lazy = false },
    { "oppiliappan/agila.vim",               lazy = false },
    { "Shatur/neovim-ayu",                   lazy = false },
    { "AlessandroYorba/Arcadia",             lazy = false },
    { "fcpg/vim-fahrenheit",                 lazy = false },
    { "cryptomilk/nightcity.nvim",           lazy = false },
    { "Rigellute/rigel",                     lazy = false },
    { "ldelossa/vimdark",                    lazy = false },
    { "windwp/wind-colors",                  lazy = false },
    { "diegoulloao/neofusion.nvim",          lazy = false },
    { "austinliuigi/smoke.nvim",             lazy = false },
    { "stefanvanburen/rams",                 lazy = false },
    { "panozzaj/print_wb",                   lazy = false },
    { "oni0002/neg.vim",                     lazy = false },
    { "nvimdev/oceanic-material",            lazy = false },
    { "murtaza-u/gruvqueen",                 lazy = false },
    { "dasupradyumna/midnight.nvim",         lazy = false },
    { "julien/vim-colors-green",             lazy = false },
    { "Heavenser/4seasons.vim",              lazy = false },
}
